### PR TITLE
fix: clean up some errors and state wonkiness

### PR DESCRIPTION
**Pull request by samsiegart**
- Fixes app crash when navigating to swap page before dapp approval/data loaded.
- Shows loading indicators instead of empty states when loading.
- Removes "connect" step since it was being skipped over anyway.

### CODE REVIEW

**Comment by samsiegart** [comment]
I don't want to spend too much time on autoswap since it will be replaced by the bounty project, but at least this prevents it from crashing the app

**Review by dckc — COMMENTED** [review]
I'm a little lost.

What are we fixing here? How would I reproduce the problem?

I'm used to unit tests for bug fixes. Is that not cost-effective here?

**Comment by samsiegart** [comment]
> What are we fixing here? How would I reproduce the problem?
> 
> I'm used to unit tests for bug fixes. Is that not cost-effective here?

Sorry, just updated the description with the various fixes/changes. The crash is pretty easy to repro just by going to treasury.agoric.app then immediately navigating to "swap". I didn't feel it was worth it to spend time writing tests since this app doesn't have unit tests set up and these crashes/issues are pretty annoying and low hanging fruit, I can give it a go if you disagree though.

**Comment by dckc** [comment]
> ... The crash is pretty easy to repro just by going to treasury.agoric.app then immediately navigating to "swap".

I get a blank page. Is that a crash?

When I go to the deployed version of this PR, I get a spinner (and the heading / nav bar doesn't go away). Does that mean it's working?

> I didn't feel it was worth it to spend time writing tests since ...

ok, that falls under "not cost-effective"

**Comment by samsiegart** [comment]
> I get a blank page. Is that a crash?

Yea

> When I go to the deployed version of this PR, I get a spinner (and the heading / nav bar doesn't go away). Does that mean it's working?

I guess this is another edge case when you visit the app without an ag-solo running. It just shows an indefinite loading state instead of a "connect to wallet" or "start your ag-solo" state. I could either try to fix that in this PR, try to fix that in another PR, or wait for the on-chain wallet which make that a non-issue.

**Review by dckc — APPROVED** [review]
I finally got around to trying this with a wallet running. Works as advertised.

**Pull request merged**
