### PR TITLE
redirect /manageVault etc. to app home page

### PR DESCRIPTION
**Pull request by dckc**
note this has to be pushed to `beta` to go live at https://treasury.agoric.app/

I'd like to look at the deploy preview first...

goal:
fixes: #10

### CODE REVIEW

**Review by katelynsills — APPROVED** [review]

**Comment by dckc** [comment]
I'm not sure this is working; I get a 404 at https://606de26f0622ce09df09886f--agoric-dapp-treasury.netlify.app/manage

**Comment by dckc** [comment]
this adds `/index.html` to the URL explicitly, which is a little ugly, but it's much nicer than a 404...

**Comment by dckc** [comment]
I'm merging this into `beta`. We have stuff on `beta` that's not in `main`, which is a little awkward...

**Comment by katelynsills** [comment]
> I'm merging this into `beta`. We have stuff on `beta` that's not in `main`, which is a little awkward...

Sounds good! everything on beta should be on main right now and vice versa, if that makes things easier. Nothing is purposefully not on main

**Pull request merged**
