### PR TITLE
Initial UI Setup for RUN Line of Credit

### PR DESCRIPTION
**Pull request by samsiegart**
author Dan Connolly <dckc@madmode.com> 1635890050 -0500
committer samsiegart <samsiegart@gmail.com> 1638923313 -0800

feat: Start RLoC UI

### CODE REVIEW

**Review by dckc — COMMENTED** [review]
This makes sense as a DRAFT PR, but the `runLoCStub.js` back-end is just a stub. Landing this on master will deploy it to treasury.agoric.app, right? I'm pretty sure we don't want to do that yet.

**Comment by samsiegart** [comment]
> This makes sense as a DRAFT PR, but the `runLoCStub.js` back-end is just a stub. Landing this on master will deploy it to treasury.agoric.app, right? I'm pretty sure we don't want to do that yet.

I've hidden the RUN line of credit stuff behind a feature flag so that we can make incremental changes. I think this is a preferred approach to maintaining a large separate feature branch. Perhaps instead of a url param we can use an env variable or something if that's not preferred.

**Comment by dckc** [comment]
Should this otherwise work? I tried to set up a vault, but when I accepted the offer, I got:

```
Error: Requested {"brand":"[Alleged: RUN brand]","value":"[332372234n]"} exceeds max {"brand":"[Alleged: RUN brand]","value":"[332323351n]"}
```

**Review by dckc — APPROVED** [review]

**Review by michaelfig — APPROVED** [review]
LGTM!

Just one concern around typing: can you please check that all the files whose JSDocs no longer explicitly `import('../../xxx')` their types instead use something like `import './types/types.js';` somewhere at the top of them.

**Comment by samsiegart** [comment]
> Just one concern around typing: can you please check that all the files whose JSDocs no longer explicitly `import('../../xxx')` their types instead use something like `import './types/types.js';` somewhere at the top of them.

Just went through and fixed all the type errors I could find. I think most of those comments were redundant and types was already being imported.

**Pull request merged**
