### PR TITLE
Merge main into beta

### PR DESCRIPTION
**Pull request by samsiegart**
refs: https://github.com/Agoric/dapp-treasury/issues/61

### CODE REVIEW

**Review by michaelfig — APPROVED** [review]
@samsiegart have you manually tested the CI-deployed website?

Approving in advance in case the answer is "yes".

**Comment by samsiegart** [comment]
> @samsiegart have you manually tested the CI-deployed website?
> 
> Approving in advance in case the answer is "yes".

Hmm I guess it's not working. I see the changes to ui/src/components/vault/NewVault.jsx showing up, but it's still pointing to the no-longer-existent "Treasury" contract instead of "VaultFactory". Is there some hurdle with the deploy script / ui/src/generated/defaults.js when deploying?

**Comment by michaelfig** [comment]
> Is there some hurdle with the deploy script / `ui/src/generated/defaults.js` when deploying?

Yes, there is a subtlety.  You'll need to modify `ui/deploy/src/generated/defaults.js` (note the extra `deploy` in that path), as that's the one that the CI automatic deploy is based on.

**Review by michaelfig — CHANGES_REQUESTED** [review]
Please manually test the CI-deployed UI instance.  Ping me when ready, and I'll approve.

**Comment by samsiegart** [comment]
> Please manually test the CI-deployed UI instance. Ping me when ready, and I'll approve.

Looks like everything's working now, thanks!

**Review by michaelfig — APPROVED** [review]
Great!

**Pull request merged**
